### ISSUE TITLE
Error while processing function <SNR>50_handle_stdout[6]..iris#api#handle_data

### ISSUE THREAD

**Issue by icyphox** [soywod/iris.vim#5]
Hey! I really like this project and I'd love to use this as my main MUA. However, when I run `:Iris`, I get the below error:

```
Error detected while processing function <SNR>50_handle_stdout[6]..iris#api#hand
le_data:
line    2:
E474: Unexpected end of input: {"success": true, "type": "select-folder", "folde
r": "INBOX", "seq": 1294, "emails": [...]
```

The `[...]` was added by me, since it lists out my mail subjects. I'm happy to provide any further information you may need.

Thanks!

**Comment by soywod** [comment]
Hey, I'm glad to hear that! Thank you for your feedback. Which version of (Ne)vim do you use? On which OS?

**Comment by icyphox** [comment]
I'm running Neovim v0.4.3 on OpenBSD.

**Comment by icyphox** [comment]
> It seems that it misses the last `}`

I'm not sure. You know what, I'll share a screenshot of the entire
traceback.

**Comment by icyphox** [comment]
![image](https://user-images.githubusercontent.com/17672379/83610940-e1810900-a59d-11ea-8e17-08763a366195.png)

**Comment by soywod** [comment]
> I'm running Neovim v0.4.3 on OpenBSD.

Mmmh strange, I'm also on Neovim v0.4.3 + ArchLinux (quite close to your config) and I don't have the problem. On the trace stack it looks like the content is being truncated (to big?). Could you check logs in `/tmp/iris.log`?

**Comment by soywod** [comment]
Also, which version of Python do you use? What returns `:echo :has('python3')`?

**Comment by icyphox** [comment]
Okay so I've pastebinned the log here: https://termbin.com/tnot
Removed the first line since it contained my password.

I have Python 3 on my system, and `:echo has('python3')` returns `0`.

**Comment by soywod** [comment]
The fact not to have `python3` support inside vim could be the reason, can you try to install it (`pip3 install --user neovim`) and see the result?

**Comment by icyphox** [comment]
Hmm, that doesn't seem to fix it. Same errors. :/

**Comment by soywod** [comment]
The python logs seem good, so the problem comes from vim that can't parse the answer. I will investigate and let you know!

**Comment by soywod** [comment]
Could you update Iris and see the result? I just want to check if the fact to have solved [this issue](https://github.com/soywod/iris.vim/issues/6) fixed yours by any chance?

**Comment by icyphox** [comment]
> Could you update Iris and see the result?

I just did. Again, I see the same errors. :(

**Comment by soywod** [comment]
I used the json from your python logs and I don't reproduce, the list shows well for me :( so I don't know where it comes from. Could you try to replace the mail chunk size by `1` (https://github.com/soywod/iris.vim/blob/master/server.py#L62) and see? If it shows well the list then it comes from a particular mail, you will need to find out which one so we can investigate.

**Comment by icyphox** [comment]
Okay, so I archived my entire inbox and started Iris afresh -- it seems
to work! I know it doesn't solve the actual problem; would you like me
to investigate further, or can we close this issue?

Also, a few suggestions:
    - I tried replying to this GitHub notification via Iris, but it
      doesn't go through -- it appears Iris doesn't set the 'In-Reply-To'
      header. GitHub email replies need this (and so does replying to an
      email thread).
    - You can use Vim's built in 'mail' filetype. It formats headers,
      subject, quotes etc. out-of-the-box.

I'll try to shoot a PR or two your way, when I find time. I made an
attempt at writing an email client -- only to drop it midway because
email sucks. But good on ya, for keeping at it!

**Comment by soywod** [comment]
> Okay, so I archived my entire inbox and started Iris afresh -- it seems
to work!

So it means it comes from a specific mail? Very strange.

Your suggestions are very interesting, I will have a look. Even if I started this plugin few years ago, the project is still young (I lost motivation in the middle also). People started to be interested in since weeks, which makes me very happy and motivates me! Your PRs are welcomed. Thank you for your help, I close the issue. Feel free to reopen if it occurs again.

**Comment by soywod** [comment]
I already created issues related to your suggestions, plus few other ones. Let me know if you want to take one of them!

**Comment by soywod** [comment]
@icyphox I fixed the `In-Reply-To` and make use of Vim's builtin mail filetype. Let me know if it works well with GitHub!

**Comment by icyphox** [comment]
Ah, turns out this error is back. I couldn't test out your fix in #19 xD

**Comment by soywod** [comment]
Damn it :( it's exactly the same? `Unexpected end of input`? I start to think it's because of one special character in one of your mail that prevent `json_decode` to work properly :/

**Comment by icyphox** [comment]
Yep, it appears to be the same. I'm baffled.

**Comment by soywod** [comment]
> I used the json from your python logs and I don't reproduce, the list shows well for me :( so I don't know where it comes from. Could you try to replace the mail chunk size by `1` (https://github.com/soywod/iris.vim/blob/master/server.py#L62) and see? If it shows well the list then it comes from a particular mail, you will need to find out which one so we can investigate.

Maybe try again this, to catch to buggy one?

**Comment by icyphox** [comment]
Ah ok. So I set `chunk_size` to 1 -- it shows only 1 mail, but it seems
to work fine now. I'm composing this from Iris!

**Comment by icyphox** [comment]
That said, I'm not sure what the offending mail is.

**Comment by soywod** [comment]
> So I set `chunk_size` to 1 -- it shows only 1 mail, but it seems
to work fine now.

Perfect, now try to increase the amount till Iris fails, so we catch the guilty mail!

> I'm composing this from Iris!

:heart_eyes:

**Comment by icyphox** [comment]
Hey, sorry. Been busy with work commitments. I'll try to get to this soon. :)

**Comment by soywod** [comment]
Don't worry, you spend already a lot of time on the improvement of this tool :) thank you btw. Meanwhile I'm fixing other issues for the `v1`. I added a [changelog](https://github.com/soywod/iris.vim/blob/master/CHANGELOG.md) and a [milestone](https://github.com/soywod/iris.vim/milestone/1) to track them.

**Comment by icyphox** [comment]
Okay so I think this might be the erroneous mail: https://termbin.com/uivet. I say "I think" because my main MUA seems to order mail differently, so I can't compare haha.

**Comment by soywod** [comment]
I sent to myself the mail and it works well within Iris :( I don't understand this bug. The big problem is I can't reproduce, which makes it not fixable for now.

**Comment by soywod** [comment]
I played a bit with the Vim's `json_decode` function, and the only way for me to get a `Unexpected end of input` is to miss the last `}`. All the rest leads to another error.

**Comment by icyphox** [comment]
Okay, after some mucking around (and asking on #vim), I managed to get
the output of `:messages` in a file. Here's the entire error dump: 
https://termbin.com/0n47

Hopefully this should be indicative of what's going wrong.

**Comment by soywod** [comment]
I think I got sth! I noticed that it's not the same error in your logs `Expected string end`, so I came to the conclusion that the data is truncated randomly. I started to search about neovim jobs and I found [this issue](https://github.com/neovim/neovim/issues/4897). In fact it's a normal neovim job behaviour! We need to wait for the EOF char `""` to occur before sending to the callback, otherwise we may have truncated content. I pushed sth, could you try? Also, could you try on Vim8+ (if you have)? Since they use different job system, it should work. Let me know.

**Comment by icyphox** [comment]
Hey so I updated Iris and tried it again—I get the same error. I don't have Vim8, let me install it and try it out.

**Comment by soywod** [comment]
I'm losing faith on this issue xD I just pushed sth where I try to concatenate
the stdout in a different way, let's see how it works for you. If it doesn't, I
will set up a verbose mode to analyse which stdout you receive. We will find
out!

Sent with Iris also <3

**Comment by soywod** [comment]
This issue is the last one of the `v1` milestone! Btw your opinion would be great: do you think sth important is missing for a simple yet solid `v1`? Do not hesitate if you have sth in mind :)

**Comment by icyphox** [comment]
Holy shit -- that seems to have fixed it! This works. :)
Neat work, my dude.

**Comment by icyphox** [comment]
I think this is plenty for a good `v1`.

**Comment by soywod** [comment]
Great :) I will prepare it soon. Let me know if it appears again (hopefully not xD)!

**Comment by soywod** [comment]
[`v1.0.0`](https://github.com/soywod/iris.vim/releases/tag/v1.0.0) ready :) thanks for you help!

**Comment by icyphox** [comment]
All good! And if you were wondering where all the stars are coming from—I shared Iris on https://lobste.rs! 

https://lobste.rs/s/lc7olr/iris_simple_mail_client_for_vim

**Comment by soywod** [comment]
I knew it!!! Awesome :) thanks a lot!
